name: continuous integration
on: [push, pull_request]

jobs:
  hello-world:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
      - name: print hello World
        run: echo hello world
